language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
install:
  - "cd code && npm install"
script:
  - "cd code && npm test"
branches:
  only:
    - master
    - beta
    - stable
